
# Loads default set of integrations. Do not remove.
default_config:

pyscript:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    custom_components.pyscript: info

binary_sensor:
  - platform: flic

spotcast:
  sp_dc: AQCe3ZribH_raek1YQMhTFm6_aS9j_fBQ__XmV-aBMxnPIknuQRA0lgFoG-zRyMhFR7K_ZzZUv33EAAEHUFAGpRk8pFXLRV9evMGBHpxxp55qgKrw949c7FwkOlSlJE3Yc1dCsTbrlFHJ5RyPMKJcCDfB97gNyk6UVUuK4MXynvWGzAsoxVzY1OMWJF0tMKYKRvim9i6ebE9y48yEHGuOO5ooibT
  sp_key: 987e9007-6e74-4705-a3af-fc3d9e5dfd58

# ----------------------------------------------------------------------------
# Booleans.
# ----------------------------------------------------------------------------
input_boolean:
  bedroom_sound_mix_none_active:
  bedroom_sound_mix_piano_seat_with_speakers_active:
  bedroom_sound_mix_desk_seat_with_speakers_active:
  bedroom_sound_mix_piano_seat_with_headphones_active:
  bedroom_sound_mix_desk_seat_with_headphones_active:
  bedroom_plug_piano_speakers:
  bedroom_plug_desk_speakers:
  bedroom_plug_piano_led_strip:
  bedroom_plug_studio_light:
  bedroom_plug_computer_monitor:
  bedroom_enable_dimmer_desk_light:
  livingroom_qn90a_ambient_mode:
  livingroom_plug_xmas_lights:
  livingroom_plug_nvidia_shield:
  diningroom_plug_xmas_lights:

# ----------------------------------------------------------------------------
# Floats.
# ----------------------------------------------------------------------------
input_number:
  bedroom_windows_pc_fader_1:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_fader_2:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_fader_3:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_fader_4:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_fader_5:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_dial_1:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_dial_2:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_dial_3:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_dial_4:
    min: 0
    max: 1
    step: 0.01
  bedroom_windows_pc_dial_5:
    min: 0
    max: 1
    step: 0.01

# ----------------------------------------------------------------------------
# Scripts.
# ----------------------------------------------------------------------------
script:
  # Dummy node. Required because Stream Deck needs to point at something.
  dummy_script:
    mode: single
    sequence:

  # Turns off every device in the bedroom. Useful to go to sleep.
  # TODO: Migrate to pyscript.
  bedroom_turn_off_everything:
    mode: single
    sequence:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.bedroom_sound_mix_name
        value: silence
    - service: light.turn_off
      data:
        entity_id:
        - light.bedroom_ceiling_light
        - light.bedroom_closet_light
        - light.bedroom_studio_light
        - light.bedroom_plug_desk_light
        - light.bedroom_plug_computer_screen
